name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"

permissions:
  contents: write
  packages: write

env:
  DOTNET_NOLOGO: true

jobs:
  build_nuget_and_publish_to_nugetorg:
    runs-on: ubuntu-latest

    steps:

      - name: Calculate version from the Commit Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - run: dotnet restore --verbosity minimal

      - run: dotnet build --configuration Release /p:ContinuousIntegrationBuild=true /p:version=${{ env.RELEASE_VERSION }}

      - run: dotnet pack --configuration Release --no-build --output ./artifacts /p:version=${{ env.RELEASE_VERSION }}

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./artifacts/*

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./artifacts/*

      - name: Publish to nuget.org
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key ${{ secrets.NUGET_TOKEN }} \
            --source https://api.nuget.org/v3/index.json
